name: Docker

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: docker build
        uses: actions/docker/cli@master
        with:
          args: build -t MRHQ-L5/l5_mission4 .
      - name: docker login
        uses: actions/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      - name: docker push
        uses: actions/docker/cli@master
        with:
          args: push MRHQ-L5/l5_mission4-node
